# pylint: skip-file
"""Add naming convention for constraints

Revision ID: 7d646be4eed8
Revises: 
Create Date: 2024-10-04 16:13:59.369968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d646be4eed8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uuid', table_name='album')
    op.create_unique_constraint(op.f('uq_album_uuid'), 'album', ['uuid'])
    op.drop_index('uuid', table_name='image')
    op.create_unique_constraint(op.f('uq_image_uuid'), 'image', ['uuid'])
    op.drop_index('uuid', table_name='tag')
    op.create_unique_constraint(op.f('uq_tag_uuid'), 'tag', ['uuid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_tag_uuid'), 'tag', type_='unique')
    op.create_index('uuid', 'tag', ['uuid'], unique=True)
    op.drop_constraint(op.f('uq_image_uuid'), 'image', type_='unique')
    op.create_index('uuid', 'image', ['uuid'], unique=True)
    op.drop_constraint(op.f('uq_album_uuid'), 'album', type_='unique')
    op.create_index('uuid', 'album', ['uuid'], unique=True)
    # ### end Alembic commands ###
